### ISSUE TITLE
ImportError: WordCompleter

### ISSUE THREAD

**Issue by immunIT** [jonathanslenders/python-prompt-toolkit#653] opened 2018-06-28 09:55 UTC
Hi, 

It seems that the release 2.0.X have some trouble to import the package WordCompleter. You can find below the thread showing the associated stacktrace.

https://github.com/immunIT/drupwn/issues/12

Best,

**Comment by jonathanslenders** [comment] 2018-06-28 20:55
As I explained in that thread, this is because ``dropwn`` is not yet upgraded to prompt_toolkit 2.0. There are more important changes then this ImportError.

Again, if you face any issues with the upgrade, let me know.
I'm closing this issue, because it's not a bug in our side.

**Closed by jonathanslenders** 2018-06-28 20:55 UTC
