### ISSUE TITLE
examples/text_editor.py exception on windows (prompt-toolkit 2.0)

### ISSUE THREAD

**Issue by skywind3000** [jonathanslenders/python-prompt-toolkit#582] opened 2018-02-01 17:30 UTC
command:
```
E:\Github\python-prompt-toolkit\examples\full-screen>python text-editor.py
```

result:
```
Traceback (most recent call last):
  File "text-editor.py", line 300, in <module>
    scroll_offset=1)),
  File "build\bdist.win32\egg\prompt_toolkit\layout\menus.py", line 196, in __init__
  File "build\bdist.win32\egg\prompt_toolkit\layout\containers.py", line 1203, in __init__
AssertionError
```

**Comment by jonathanslenders** [comment] 2018-02-07 18:26
Hi @skywind3000,

I'm not able to reproduce this. Can you make sure that you have the latest prompt_toolkit (the 2.0  branch)? If this still raises an exception,  then it would be great if you could print the values of the assertion which fails.

Thanks!

**Comment by jonathanslenders** [comment] 2018-10-21 09:12
Closing this. Let's open it again, if either somebody can reproduce it (if it's still an issue), or if we know the actual exception.

**Closed by jonathanslenders** 2018-10-21 09:12 UTC
